services:
  course:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      APP_ENV: production
      VIDEOS_DIR: /videos
      DATA_DIR: /data
      QSV_DEVICE: /dev/dri/renderD128
    volumes:
      - /home/jaw/plex/videos:/videos:ro
      - /home/jaw/data/course:/data
    devices:
      - /dev/dri:/dev/dri
